# Generated by Django 4.2.5 on 2023-10-26 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entregatarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='archivo_entrega',
            field=models.FileField(null=True, upload_to='entregas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='task',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contenido_profesor/'),
        ),
    ]
