# Generated by Django 4.2.7 on 2023-12-04 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
