# Generated by Django 4.2.5 on 2023-10-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entregatarea_archivo_entrega_task_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatarea',
            name='archivo_entrega',
        ),
        migrations.RemoveField(
            model_name='task',
            name='archivo',
        ),
    ]
