# Generated by Django 4.2.5 on 2023-11-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
