# Generated by Django 4.2.7 on 2023-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teacher_password',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
