# Generated by Django 4.2.5 on 2023-11-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usercustom_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
