# Generated by Django 4.2.5 on 2023-11-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
