# Generated by Django 4.2.7 on 2023-12-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher_candidate',
            field=models.BooleanField(default=True),
        ),
    ]
