# Generated by Django 4.2.5 on 2023-11-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
