# Generated by Django 4.2.7 on 2023-12-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_is_teacher_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher_candidate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_password',
        ),
    ]
