# Generated by Django 4.2.7 on 2023-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_is_teacher_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
