# Generated by Django 4.2.5 on 2023-11-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_entregatarea_informacion_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
