# Generated by Django 4.2.6 on 2023-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_entregatarea_confirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
