# Generated by Django 4.2.6 on 2023-11-21 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_entregatarea_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
