# Generated by Django 4.2.5 on 2023-11-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_entregatarea_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatarea',
            name='confirmada',
        ),
        migrations.AlterField(
            model_name='entregatarea',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
