# Generated by Django 4.2.7 on 2023-12-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_password',
        ),
    ]
