# Generated by Django 4.2.7 on 2023-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_entregatarea_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
