# Generated by Django 4.2.7 on 2023-12-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customuser_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
