# Generated by Django 4.2.7 on 2023-12-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_customuser_is_teacher_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='approved_by_admin',
        ),
    ]
