# Generated by Django 4.2.5 on 2023-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_entregatarea_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
