# Generated by Django 4.2.5 on 2023-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_entregatarea_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='anulada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='bloqueada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
