# Generated by Django 4.2.7 on 2023-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_teacher_approved_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
