# Generated by Django 4.2.7 on 2023-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_archivos_adjuntos_task_archivos_adjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='comentarios_profesor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
