# Generated by Django 4.2.5 on 2023-09-27 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='age',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='identy',
            field=models.PositiveIntegerField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
