# Generated by Django 4.2.5 on 2023-09-27 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usercustom_age_usercustom_identy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='identy',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='identity',
            field=models.PositiveIntegerField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Numero de identidad'),
        ),
    ]
