# Generated by Django 4.2.5 on 2023-09-29 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usercustom_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='identity',
            field=models.PositiveIntegerField(db_index=True, default=-1, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Numero de identidad'),
        ),
    ]
